version: "3"
services:
  app:
    build: .
    volumes:
      - ./dist:/usr/src/app/dist/
    #ports:
    #  - "3000:3000"
    environment:
      - NODE_ENV=${NODE_ENV}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - LOG_DIRECTORY=${LOG_DIRECTORY}
      - LOG_LEVEL=${LOG_LEVEL}
      - LOG_OUTPUT_MODE=${LOG_OUTPUT_MODE}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_CACHE_TIMEOUT=${REDIS_CACHE_TIMEOUT}
      - SERVER_PORT=${SERVER_PORT}
      - SERVER_KEY_PRIVATE=${SERVER_KEY_PRIVATE}
      - SERVER_KEY_PUBLIC=${SERVER_KEY_PUBLIC}
      - JWT_TOKEN_EXPIRED=${JWT_TOKEN_EXPIRED}
    depends_on:
      - svt-db
      - svt-redis_cache
    networks:
      - app_network
     # Optionally, add restart policy
    #restart: unless-stopped
  
  svt-db:
    image: mysql:8.0
    container_name: svt-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    expose:
      # Opens port 3306 on the container
      - '3306'
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_network
  
  svt-redis_cache:
    image: "redis:latest"
    container_name: svt-redis_cache
    ports:
      - "6379:6379"  # Porta di Redis
    expose:
      # Opens port 3306 on the container
      - '6379'
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  db_data:
  