services:
  app:
    build: .
    command: ["/wait-for-it.sh", "svt-db:3306", "--", "npm", "run", "migrate-and-seed", "--", "npm", "run", "start"]
    volumes:
      - .:/app
      - ./.keys/:/app/.keys/
    ports:
      - "3000:3000"
    expose:
      # Opens port 3306 on the container
      - "3000"
    environment:
      - APP_ENV=${APP_ENV}
      - NODE_ENV=${NODE_ENV}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - LOG_DIRECTORY=${LOG_DIRECTORY}
      - LOG_LEVEL=${LOG_LEVEL}
      - LOG_OUTPUT_MODE=${LOG_OUTPUT_MODE}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_CACHE_TIMEOUT=${REDIS_CACHE_TIMEOUT}
      - SERVER_PORT=${SERVER_PORT}
      - JWT_PRIVATE_KEY=${JWT_PRIVATE_KEY}
      - JWT_PUBLIC_KEY=${JWT_PUBLIC_KEY}
      - JWT_TOKEN_EXPIRED=${JWT_TOKEN_EXPIRED}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - RABBITMQ_URL=${RABBITMQ_URL}
      - SPEED_TOLLERANCE=${SPEED_TOLLERANCE}
      - IMAGE_PATH=${IMAGE_PATH}
      - IMAGE_TYPE=${IMAGE_TYPE}
      - IMAGE_TYPE=${IMAGE_FILE}
    depends_on:
      - svt-db
      - svt-redis_cache
      - svt-rabbitmq
    networks:
      - app_network
     # Optionally, add restart policy
    #restart: unless-stopped
  
  svt-db:
    image: mysql:8.0
    container_name: svt-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    expose:
      # Opens port 3306 on the container
      - '3306'
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_network
  
  svt-redis_cache:
    image: "redis:latest"
    container_name: svt-redis_cache
    ports:
      - "6379:6379"  # Porta di Redis
    expose:
      # Opens port 3306 on the container
      - '6379'
    networks:
      - app_network

  svt-rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"   # Porta per il protocollo AMQP
      - "15672:15672" # Porta per la RabbitMQ Management UI
    expose:
      # Opens port 3306 on the container
      - '15672'
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  db_data:  