version: "3"
services:
  app:
    build: .
    volumes:
      - ./dist:/usr/src/app/dist/
    #ports:
    #  - "3000:3000"
    environment:
      - NODE_ENV=${NODE_ENV}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - LOG_DIRECTORY=${LOG_DIRECTORY}
      - LOG_LEVEL=${LOG_LEVEL}
      - LOG_OUTPUT_MODE=${LOG_OUTPUT_MODE}