name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Run Linter
      run: npm run lint

    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Start Docker Compose stack
      env:
        APP_ENV: ${{ secrets.APP_ENV }}
        NODE_ENV: ${{ secrets.NODE_ENV }}
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_PORT: ${{ secrets.DB_PORT }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASS: ${{ secrets.DB_PASS }}
        DB_NAME: ${{ secrets.DB_NAME }}
        LOG_DIRECTORY: ${{ secrets.LOG_DIRECTORY }}
        LOG_LEVEL: ${{ secrets.LOG_LEVEL }}
        LOG_OUTPUT_MODE: ${{ secrets.LOG_OUTPUT_MODE }}
        REDIS_HOST: ${{ secrets.REDIS_HOST }}
        REDIS_PORT: ${{ secrets.REDIS_PORT }}
        REDIS_CACHE_TIMEOUT: ${{ secrets.REDIS_CACHE_TIMEOUT }}
        SERVER_PORT: ${{ secrets.SERVER_PORT }}
        JWT_PRIVATE_KEY: ${{ secrets.JWT_PRIVATE_KEY }}
        JWT_PUBLIC_KEY: ${{ secrets.JWT_PUBLIC_KEY }}
        JWT_TOKEN_EXPIRED: ${{ secrets.JWT_TOKEN_EXPIRED }}
        MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
        MYSQL_USER: ${{ secrets.MYSQL_USER }}
        MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
        MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
      run: docker-compose up -d app svt-db svt-redis_cache  # Avvia solo i servizi

    - name: Run Migrations
      run: 
        export NODE_ENV=test
        npm run migrate

    - name: Run Seeders
      run: 
        export NODE_ENV=test
        npm run seed

    - name: Run Tests
      run: docker-compose run svt-test  # Esegui i test separatamente dopo migrate e seed


    - name: Build Docker Image
      run: docker build -t lxpool/svt-app:latest .

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Push Docker Image
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/svt-app:latest

    - name: Shutdown Docker Compose stack
      run: docker-compose down